//
//  MainPresenter.swift
//  Medium-CleanSwift
//
//  Created by Uladzislau Komar on 30.01.23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic {
    func presentFetchedCartoonCharacters(response: Main.desplayCartoonCharacters.Response)
}

class MainPresenter: MainPresentationLogic {
    weak var viewController: MainDisplayLogic?
    
    // MARK: Do something
    
    func presentFetchedCartoonCharacters(response: Main.desplayCartoonCharacters.Response) {
        let characterArray = response.characters
        var characterInformation: [(String, String)] = []
        for character in characterArray {
            characterInformation.append((character.name, character.species))
        }
        let viewModel = Main.desplayCartoonCharacters.ViewModel(characterInformation: characterInformation)
        viewController?.addCharactersToVariable(viewModel: viewModel)
    }
}
