//
//  MainPresenter.swift
//  Medium-CleanSwift
//
//  Created by Uladzislau Komar on 30.01.23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic {
    func presentFetchedCartoonCharacters(response: Main.displayCartoonCharacters.Response)
}

class MainPresenter: MainPresentationLogic {
    weak var viewController: MainDisplayLogic?
    
    // MARK: Do something
    
    func presentFetchedCartoonCharacters(response: Main.displayCartoonCharacters.Response) {
        let characterArray = response.characters
        var characterInformation: [Main.displayCartoonCharacters.ViewModel.characterInformationModel] = []
        for character in characterArray {
            let characterModel = Main.displayCartoonCharacters.ViewModel.characterInformationModel(
                id: character.id,
                name: character.name,
                species: character.species)
            characterInformation.append(characterModel)
        }
        let viewModel = Main.displayCartoonCharacters.ViewModel(characterInformation: characterInformation)
        viewController?.addCharactersToVariable(viewModel: viewModel)
    }
}
