//
//  DetailedInteractor.swift
//  Medium-CleanSwift
//
//  Created by Uladzislau Komar on 30.01.23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailedBusinessLogic {
    func fetchDetailedInformation(request: Detailed.Something.Request)
}

protocol DetailedDataStore {
    var character: CharResult? { get set }
}

class DetailedInteractor: DetailedBusinessLogic, DetailedDataStore {
    var character: CharResult?
    let network = Network()
    var presenter: DetailedPresentationLogic?
    var worker: DetailedWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func fetchDetailedInformation(request: Detailed.Something.Request) {
        guard let imageString = character?.image,
              let url = URL(string: imageString) else {
            return
        }
                
        network.loadImage(for: url) { [weak self] result in
            DispatchQueue.main.async {
                switch result {
                case .success(let fetchedImage):
                    let response = Detailed.Something.Response(
                        name: self?.character?.name ?? "",
                        species: self?.character?.species ?? "",
                        image: fetchedImage)
                    self?.presenter?.presentDetailedInformation(response: response)
                case .failure(_):
                    break
                }
            }
        }
        
        
    }
}
