//
//  DetailedPresenter.swift
//  Medium-CleanSwift
//
//  Created by Uladzislau Komar on 30.01.23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailedPresentationLogic {
    func presentSomething(response: Detailed.Something.Response)
}

class DetailedPresenter: DetailedPresentationLogic {
    weak var viewController: DetailedDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Detailed.Something.Response) {
        let viewModel = Detailed.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
