//
//  DetailedPresenter.swift
//  Medium-CleanSwift
//
//  Created by Uladzislau Komar on 30.01.23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailedPresentationLogic {
    func presentDetailedInformation(response: Detailed.Something.Response)
}

class DetailedPresenter: DetailedPresentationLogic {
    weak var viewController: DetailedDisplayLogic?
    
    // MARK: Do something
    
    func presentDetailedInformation(response: Detailed.Something.Response) {
        let name = "Character name: " + response.name
        let species = "Character species: " + response.species
        let viewModel = Detailed.Something.ViewModel(
            name: name,
            species: species,
            image: response.image)
        viewController?.displayCharacterInformation(viewModel: viewModel)
    }
}
