//
//  TwoInteractor.swift
//  CleanSwiftProject
//
//  Created by Uladzislau Komar on 21.01.23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TwoBusinessLogic {
    func doSomething(request: Two.Something.Request)
}

protocol TwoDataStore {
    var name: String { get set }
}

class TwoInteractor: TwoBusinessLogic, TwoDataStore {
    var presenter: TwoPresentationLogic?
    var worker: TwoWorker?
    var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: Two.Something.Request) {
        worker = TwoWorker()
        worker?.doSomeWork()
        
        let response = Two.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
