//
//  OneInteractor.swift
//  CleanSwiftProject
//
//  Created by Uladzislau Komar on 21.01.23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OneBusinessLogic {
    func doSomething(request: One.Something.Request)
    func setNewValue(value: String)
}

protocol OneDataStore {
    var name: String { get set }
}

class OneInteractor: OneBusinessLogic, OneDataStore {
    var presenter: OnePresentationLogic?
    var worker: OneWorker?
    var name: String = ""
    
    // MARK: Do something
    
    func setNewValue(value: String) {
        name = value
    }
    
    func doSomething(request: One.Something.Request) {
        worker = OneWorker()
        worker?.doSomeWork()
        
        let response = One.Something.Response()
        presenter?.presentSomething(response: response)
    }
}

