//
//  OnePresenter.swift
//  CleanSwiftProject
//
//  Created by Uladzislau Komar on 21.01.23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OnePresentationLogic {
    func presentSomething(response: One.Something.Response)
}

class OnePresenter: OnePresentationLogic {
    weak var viewController: OneDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: One.Something.Response) {
        let viewModel = One.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
